[package]
name = "quorum_core"
version = "0.1.0"
edition = "2021"

[lib]
name = "quorum_core"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.19", features = ["extension-module"] }
